# CONFIGURATION LOCAL (IDE)-product
spring.application.name=product-service
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:MonNouveauMotDePasse123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keycloak / OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/microservices-realm
keycloak.auth-server-url=http://localhost:7080
keycloak.realm=microservices-realm
keycloak.client-id=product-service
keycloak.client-secret=${KEYCLOAK_SECRET:NS5HN0aGzU7UzqYCelKUK52XqAVPZ8BK}

