# CONFIGURATION LOCAL (IDE)-orders
spring.application.name=order-service
server.port=8082

# Database (Chaque service a sa propre DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:MonNouveauMotDePasse123}
spring.datasource.driver-class-name=org.postgresql.Driver
# Pour PostgreSQL / MySQL
spring.jpa.hibernate.ddl-auto=update

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Feign Client (URL du Product Service)
application.config.product-url=http://localhost:8081
product.service.url=localhost:8081

# Configuration Security / Keycloak (Requis pour JwtDecoder)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/microservices-realm

# Facultatif : Si tu utilises ces propriétés dans ton code
keycloak.auth-server-url=http://localhost:7080
keycloak.realm=microservices-realm
keycloak.client-id=order-service
# Remplace par le secret spécifique à order-service si tu en as un dans Keycloak
keycloak.client-secret=${KEYCLOAK_SECRET:TON_SECRET_KEYCLOAK_ORDER}