# CONFIGURATION DOCKER-notification
server.port=8080
spring.datasource.url=jdbc:postgresql://postgres:5432/orders_db
spring.kafka.bootstrap-servers=localhost:29092
application.config.product-url=http://product-service:8080