# CONFIGURATION DOCKER-product
server.port=8080
spring.datasource.url=jdbc:postgresql://postgres-db:5432/microservices_db
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:7080/realms/microservices-realm
keycloak.auth-server-url=http://keycloak:7080